apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-processor-5908
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/auth-processor-5908
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
